name: Issue Management

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: EddieHubCommunity/gh-action-open-source-labels@v0.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner-name: ${{ github.repository_owner }}
          repository-name: ${{ github.event.repository.name }}
  stale:
    if: ${{ github.event_name != 'push' }}
    needs: labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Stale issue message"
          stale-pr-message: "Stale pull request message"
          stale-issue-label: "no issue activity"
          stale-pr-label: "no issue activity"
